///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CIT_Web2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CIT_Web2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c5be42e6-b486-4f69-bb41-3d765222f1ab")]
    public partial class CIT_Web2Repository : RepoGenBaseFolder
    {
        static CIT_Web2Repository instance = new CIT_Web2Repository();
        CIT_Web2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the CIT_Web2Repository element repository.
        /// </summary>
        [RepositoryFolder("c5be42e6-b486-4f69-bb41-3d765222f1ab")]
        public static CIT_Web2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CIT_Web2Repository() 
            : base("CIT_Web2Repository", "/", null, 0, false, "c5be42e6-b486-4f69-bb41-3d765222f1ab", ".\\RepositoryImages\\CIT_Web2Repositoryc5be42e6.rximgres")
        {
            _applicationundertest = new CIT_Web2RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c5be42e6-b486-4f69-bb41-3d765222f1ab")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("448ab23e-2299-458d-b954-6dc5503deb9f")]
        public virtual CIT_Web2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CIT_Web2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("448ab23e-2299-458d-b954-6dc5503deb9f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _大学案内Info;
            RepoItemInfo _大学案内1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.it-chiba.ac.jp']", parentFolder, 30000, null, false, "448ab23e-2299-458d-b954-6dc5503deb9f", "")
            {
                _大学案内Info = new RepoItemInfo(this, "大学案内", ".//div[#'gnavi']/nav//span[@innertext='大学案内']", 30000, null, "e3f03078-bccc-4337-8cb4-252dcff5eaba");
                _大学案内1Info = new RepoItemInfo(this, "大学案内1", ".//div[#'main']//h1[@innertext='大学案内']", 30000, null, "c8f16d25-d989-450a-a7cc-65fe9abc95e3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("448ab23e-2299-458d-b954-6dc5503deb9f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("448ab23e-2299-458d-b954-6dc5503deb9f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 大学案内 item.
            /// </summary>
            [RepositoryItem("e3f03078-bccc-4337-8cb4-252dcff5eaba")]
            public virtual Ranorex.SpanTag 大学案内
            {
                get
                {
                    return _大学案内Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The 大学案内 item info.
            /// </summary>
            [RepositoryItemInfo("e3f03078-bccc-4337-8cb4-252dcff5eaba")]
            public virtual RepoItemInfo 大学案内Info
            {
                get
                {
                    return _大学案内Info;
                }
            }

            /// <summary>
            /// The 大学案内1 item.
            /// </summary>
            [RepositoryItem("c8f16d25-d989-450a-a7cc-65fe9abc95e3")]
            public virtual Ranorex.H1Tag 大学案内1
            {
                get
                {
                    return _大学案内1Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The 大学案内1 item info.
            /// </summary>
            [RepositoryItemInfo("c8f16d25-d989-450a-a7cc-65fe9abc95e3")]
            public virtual RepoItemInfo 大学案内1Info
            {
                get
                {
                    return _大学案内1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
