///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CIT_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CIT_WebRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f583a8b5-5006-49e4-b946-9e93dcfe1749")]
    public partial class CIT_WebRepository : RepoGenBaseFolder
    {
        static CIT_WebRepository instance = new CIT_WebRepository();
        CIT_WebRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        CIT_WebRepositoryFolders.千葉工業大学AppFolder _千葉工業大学;

        /// <summary>
        /// Gets the singleton class instance representing the CIT_WebRepository element repository.
        /// </summary>
        [RepositoryFolder("f583a8b5-5006-49e4-b946-9e93dcfe1749")]
        public static CIT_WebRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CIT_WebRepository() 
            : base("CIT_WebRepository", "/", null, 0, false, "f583a8b5-5006-49e4-b946-9e93dcfe1749", ".\\RepositoryImages\\CIT_WebRepositoryf583a8b5.rximgres")
        {
            _applicationundertest = new CIT_WebRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _千葉工業大学 = new CIT_WebRepositoryFolders.千葉工業大学AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f583a8b5-5006-49e4-b946-9e93dcfe1749")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a758fe24-4bfc-4a34-b160-26a0658864ba")]
        public virtual CIT_WebRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The 千葉工業大学 folder.
        /// </summary>
        [RepositoryFolder("bbef0afc-38a4-4f36-a3c5-ffb08ff3975e")]
        public virtual CIT_WebRepositoryFolders.千葉工業大学AppFolder 千葉工業大学
        {
            get { return _千葉工業大学; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CIT_WebRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a758fe24-4bfc-4a34-b160-26a0658864ba")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "a758fe24-4bfc-4a34-b160-26a0658864ba", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a758fe24-4bfc-4a34-b160-26a0658864ba")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a758fe24-4bfc-4a34-b160-26a0658864ba")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The 千葉工業大学AppFolder folder.
        /// </summary>
        [RepositoryFolder("bbef0afc-38a4-4f36-a3c5-ffb08ff3975e")]
        public partial class 千葉工業大学AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpswwwitchibaacjpinstituteInfo;
            RepoItemInfo _大学案内Info;

            /// <summary>
            /// Creates a new 千葉工業大学  folder.
            /// </summary>
            public 千葉工業大学AppFolder(RepoGenBaseFolder parentFolder) :
                    base("千葉工業大学", "/dom[@domain='www.it-chiba.ac.jp']", parentFolder, 30000, null, false, "bbef0afc-38a4-4f36-a3c5-ffb08ff3975e", "")
            {
                _httpswwwitchibaacjpinstituteInfo = new RepoItemInfo(this, "HttpsWwwItChibaAcJpInstitute", ".//div[#'gnavi']/nav//a[@href>'https://www.it-chiba.ac.j']", 30000, null, "acde49a5-7aa3-4673-90de-3234c5cf43bd");
                _大学案内Info = new RepoItemInfo(this, "大学案内", ".//div[#'main']//h1[@innertext='大学案内']", 30000, null, "31680874-e27b-4f7e-bbc6-3fb2c693e948");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bbef0afc-38a4-4f36-a3c5-ffb08ff3975e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bbef0afc-38a4-4f36-a3c5-ffb08ff3975e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwItChibaAcJpInstitute item.
            /// </summary>
            [RepositoryItem("acde49a5-7aa3-4673-90de-3234c5cf43bd")]
            public virtual Ranorex.ATag HttpsWwwItChibaAcJpInstitute
            {
                get
                {
                    return _httpswwwitchibaacjpinstituteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwItChibaAcJpInstitute item info.
            /// </summary>
            [RepositoryItemInfo("acde49a5-7aa3-4673-90de-3234c5cf43bd")]
            public virtual RepoItemInfo HttpsWwwItChibaAcJpInstituteInfo
            {
                get
                {
                    return _httpswwwitchibaacjpinstituteInfo;
                }
            }

            /// <summary>
            /// The 大学案内 item.
            /// </summary>
            [RepositoryItem("31680874-e27b-4f7e-bbc6-3fb2c693e948")]
            public virtual Ranorex.H1Tag 大学案内
            {
                get
                {
                    return _大学案内Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The 大学案内 item info.
            /// </summary>
            [RepositoryItemInfo("31680874-e27b-4f7e-bbc6-3fb2c693e948")]
            public virtual RepoItemInfo 大学案内Info
            {
                get
                {
                    return _大学案内Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
