///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CIT_Web3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CIT_Web3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e6206a2d-c9f7-4b28-b3e1-2d2d702c6d73")]
    public partial class CIT_Web3Repository : RepoGenBaseFolder
    {
        static CIT_Web3Repository instance = new CIT_Web3Repository();
        CIT_Web3RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the CIT_Web3Repository element repository.
        /// </summary>
        [RepositoryFolder("e6206a2d-c9f7-4b28-b3e1-2d2d702c6d73")]
        public static CIT_Web3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CIT_Web3Repository() 
            : base("CIT_Web3Repository", "/", null, 0, false, "e6206a2d-c9f7-4b28-b3e1-2d2d702c6d73", ".\\RepositoryImages\\CIT_Web3Repositorye6206a2d.rximgres")
        {
            _applicationundertest = new CIT_Web3RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e6206a2d-c9f7-4b28-b3e1-2d2d702c6d73")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("84708a3f-dff5-404a-b75a-b336f3928a9f")]
        public virtual CIT_Web3RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CIT_Web3RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("84708a3f-dff5-404a-b75a-b336f3928a9f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _大学案内Info;
            RepoItemInfo _大学案内1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.it-chiba.ac.jp']", parentFolder, 30000, null, false, "84708a3f-dff5-404a-b75a-b336f3928a9f", "")
            {
                _大学案内Info = new RepoItemInfo(this, "大学案内", ".//div[#'gnavi']/nav//span[@innertext='大学案内']", 30000, null, "38e79795-c561-4516-b0b4-2a060dc0d52e");
                _大学案内1Info = new RepoItemInfo(this, "大学案内1", ".//div[#'main']//h1[@innertext='大学案内']", 30000, null, "eaa1ca5c-70d1-45ff-9b1d-776e9d44d52a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84708a3f-dff5-404a-b75a-b336f3928a9f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84708a3f-dff5-404a-b75a-b336f3928a9f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 大学案内 item.
            /// </summary>
            [RepositoryItem("38e79795-c561-4516-b0b4-2a060dc0d52e")]
            public virtual Ranorex.SpanTag 大学案内
            {
                get
                {
                    return _大学案内Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The 大学案内 item info.
            /// </summary>
            [RepositoryItemInfo("38e79795-c561-4516-b0b4-2a060dc0d52e")]
            public virtual RepoItemInfo 大学案内Info
            {
                get
                {
                    return _大学案内Info;
                }
            }

            /// <summary>
            /// The 大学案内1 item.
            /// </summary>
            [RepositoryItem("eaa1ca5c-70d1-45ff-9b1d-776e9d44d52a")]
            public virtual Ranorex.H1Tag 大学案内1
            {
                get
                {
                    return _大学案内1Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The 大学案内1 item info.
            /// </summary>
            [RepositoryItemInfo("eaa1ca5c-70d1-45ff-9b1d-776e9d44d52a")]
            public virtual RepoItemInfo 大学案内1Info
            {
                get
                {
                    return _大学案内1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
