///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace citweb
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the citwebRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("be8a31f7-5c66-411f-8b28-21eb2948ec8f")]
    public partial class citwebRepository : RepoGenBaseFolder
    {
        static citwebRepository instance = new citwebRepository();
        citwebRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        citwebRepositoryFolders.千葉工業大学GoogleChromeAppFolder _千葉工業大学googlechrome;
        citwebRepositoryFolders.SavePasswordForFtpTechmatrixCoJpAppFolder _savepasswordforftptechmatrixcojp;

        /// <summary>
        /// Gets the singleton class instance representing the citwebRepository element repository.
        /// </summary>
        [RepositoryFolder("be8a31f7-5c66-411f-8b28-21eb2948ec8f")]
        public static citwebRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public citwebRepository() 
            : base("citwebRepository", "/", null, 0, false, "be8a31f7-5c66-411f-8b28-21eb2948ec8f", ".\\RepositoryImages\\citwebRepositorybe8a31f7.rximgres")
        {
            _applicationundertest = new citwebRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _千葉工業大学googlechrome = new citwebRepositoryFolders.千葉工業大学GoogleChromeAppFolder(this);
            _savepasswordforftptechmatrixcojp = new citwebRepositoryFolders.SavePasswordForFtpTechmatrixCoJpAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("be8a31f7-5c66-411f-8b28-21eb2948ec8f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("87d71658-4c69-4db0-afb5-a459581f1680")]
        public virtual citwebRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The 千葉工業大学GoogleChrome folder.
        /// </summary>
        [RepositoryFolder("b86ae4c4-2ec4-48e8-97c2-44981242acef")]
        public virtual citwebRepositoryFolders.千葉工業大学GoogleChromeAppFolder 千葉工業大学GoogleChrome
        {
            get { return _千葉工業大学googlechrome; }
        }

        /// <summary>
        /// The SavePasswordForFtpTechmatrixCoJp folder.
        /// </summary>
        [RepositoryFolder("34f39b8e-17f8-4ca0-a85e-7229b907c435")]
        public virtual citwebRepositoryFolders.SavePasswordForFtpTechmatrixCoJpAppFolder SavePasswordForFtpTechmatrixCoJp
        {
            get { return _savepasswordforftptechmatrixcojp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class citwebRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("87d71658-4c69-4db0-afb5-a459581f1680")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _大学案内Info;
            RepoItemInfo _大学案内1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.it-chiba.ac.jp']", parentFolder, 30000, null, false, "87d71658-4c69-4db0-afb5-a459581f1680", "")
            {
                _大学案内Info = new RepoItemInfo(this, "大学案内", ".//div[#'gnavi']/nav//span[@innertext='大学案内']", "", 30000, null, "36092fd2-7066-45bc-a9db-c57faacd6df5");
                _大学案内1Info = new RepoItemInfo(this, "大学案内1", ".//div[#'main']//h1[@innertext='大学案内']", "", 30000, null, "89914804-5db3-4797-bbf5-f532858b219e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("87d71658-4c69-4db0-afb5-a459581f1680")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("87d71658-4c69-4db0-afb5-a459581f1680")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 大学案内 item.
            /// </summary>
            [RepositoryItem("36092fd2-7066-45bc-a9db-c57faacd6df5")]
            public virtual Ranorex.SpanTag 大学案内
            {
                get
                {
                    return _大学案内Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The 大学案内 item info.
            /// </summary>
            [RepositoryItemInfo("36092fd2-7066-45bc-a9db-c57faacd6df5")]
            public virtual RepoItemInfo 大学案内Info
            {
                get
                {
                    return _大学案内Info;
                }
            }

            /// <summary>
            /// The 大学案内1 item.
            /// </summary>
            [RepositoryItem("89914804-5db3-4797-bbf5-f532858b219e")]
            public virtual Ranorex.H1Tag 大学案内1
            {
                get
                {
                    return _大学案内1Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The 大学案内1 item info.
            /// </summary>
            [RepositoryItemInfo("89914804-5db3-4797-bbf5-f532858b219e")]
            public virtual RepoItemInfo 大学案内1Info
            {
                get
                {
                    return _大学案内1Info;
                }
            }
        }

        /// <summary>
        /// The 千葉工業大学GoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("b86ae4c4-2ec4-48e8-97c2-44981242acef")]
        public partial class 千葉工業大学GoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element804915744Info;

            /// <summary>
            /// Creates a new 千葉工業大学GoogleChrome  folder.
            /// </summary>
            public 千葉工業大学GoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("千葉工業大学GoogleChrome", "/form[@title='千葉工業大学 - Google Chrome']", parentFolder, 30000, null, true, "b86ae4c4-2ec4-48e8-97c2-44981242acef", "")
            {
                _element804915744Info = new RepoItemInfo(this, "Element804915744", "element[@controlid='804915744']", "", 30000, null, "48dcc0f5-2cf2-4f15-8ac4-ea27a9fecebf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b86ae4c4-2ec4-48e8-97c2-44981242acef")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b86ae4c4-2ec4-48e8-97c2-44981242acef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element804915744 item.
            /// </summary>
            [RepositoryItem("48dcc0f5-2cf2-4f15-8ac4-ea27a9fecebf")]
            public virtual Ranorex.Unknown Element804915744
            {
                get
                {
                    return _element804915744Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element804915744 item info.
            /// </summary>
            [RepositoryItemInfo("48dcc0f5-2cf2-4f15-8ac4-ea27a9fecebf")]
            public virtual RepoItemInfo Element804915744Info
            {
                get
                {
                    return _element804915744Info;
                }
            }
        }

        /// <summary>
        /// The SavePasswordForFtpTechmatrixCoJpAppFolder folder.
        /// </summary>
        [RepositoryFolder("34f39b8e-17f8-4ca0-a85e-7229b907c435")]
        public partial class SavePasswordForFtpTechmatrixCoJpAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _neverInfo;

            /// <summary>
            /// Creates a new SavePasswordForFtpTechmatrixCoJp  folder.
            /// </summary>
            public SavePasswordForFtpTechmatrixCoJpAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SavePasswordForFtpTechmatrixCoJp", "/form[@title>'Save password for ftp.tec']", parentFolder, 30000, null, true, "34f39b8e-17f8-4ca0-a85e-7229b907c435", "")
            {
                _neverInfo = new RepoItemInfo(this, "Never", "element[@accessiblename>'Save password for ftp.tec']/container/container[@accessiblerole='Pane']/container[@accessiblerole='Pane']/?/?/button[@accessiblename='Never']", "", 30000, null, "f8cafd86-b04a-47a8-a281-6819228c6fab");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34f39b8e-17f8-4ca0-a85e-7229b907c435")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34f39b8e-17f8-4ca0-a85e-7229b907c435")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Never item.
            /// </summary>
            [RepositoryItem("f8cafd86-b04a-47a8-a281-6819228c6fab")]
            public virtual Ranorex.Button Never
            {
                get
                {
                    return _neverInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Never item info.
            /// </summary>
            [RepositoryItemInfo("f8cafd86-b04a-47a8-a281-6819228c6fab")]
            public virtual RepoItemInfo NeverInfo
            {
                get
                {
                    return _neverInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
